version: '3.8'

services:
  web:
    image: realm74/simplesolutions:latest
    restart: always
    volumes:
      - .:/code
    command:
      sh -c "python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"
    env_file:
      - .env
