# Generated by Django 4.2.7 on 2023-12-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_discount_alter_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USD', 'usd'), ('EUR', 'eur')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
